# SPDX-FileCopyrightText: 2026 Guido Wolf Reichert <gwr@bsl-support.de> and contributors
# SPDX-License-Identifier: EUPL-1.2+

coverage:
  status:
    patch:
      default:
        informational: true
