name = "ReuseLicensing"
uuid = "de4d323f-34a2-45c1-b1df-90653b04f4ca"
authors = ["Guido Wolf Reichert <gwr@bsl-support.de>", "contributors"]
version = "0.2.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
TOML = "1"
julia = "1.10"

[reuse_licensing]
reuse_specification_version = "3.3"
spdx_license_list_version = "3.28.0"
package_license_expression = "EUPL-1.2+"
package_copyright_notice = "Copyright © 2026 Guido Wolf Reichert and contributors"
package_license_file = "LICENSE"
