# REUSE.toml
# Part of ReuseLicensing

version = 1

# project artifacts and tooling
[[annotations]]
path = [
    ".gitattributes",
    ".gitignore",
    ".github/**",
    ".vscode/**",
    ".*.yml",
    ".drone.star",
    "CITATION.bib",
    "CODEOWNERS",
    ".JuliaFormatter.toml",
    "Project.toml",
    "Manifest.toml",
    "docs/make.jl",
    "docs/Project.toml",
    "docs/Manifest.toml",
    "test/Project.toml",
    "test/Manifest.toml",
    "scripts/Project.toml",
    "scripts/Manifest.toml",
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert <gwr@bsl-support.de>"
SPDX-License-Identifier = "CC0-1.0"

# documentation assets
[[annotations]]
path = ["docs/src/assets/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert <gwr@bsl-support.de>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# documentation source texts
[[annotations]]
path = ["README.md", "docs/*.md", "docs/src/**/*.md"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert <gwr@bsl-support.de>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# spdx/license-list-data
# source: https://github.com/spdx/license-list-data
[[annotations]]
path = "data/spdx-license-list-data/**"
precedence = "closest"
SPDX-FileCopyrightText = "SPDX contributors to the SPDX License List"
SPDX-License-Identifier = "CC0-1.0"
