# REUSE.toml
# Part of ReuseLicensing

version = 1

[[annotations]]
path = [
    ".gitattributes",
    ".gitignore",
    ".github/**",
    ".vscode/**",
    ".licensing/**",
    ".*.yml",
    ".drone.star",
    "CITATION.bib",
    "CODEOWNERS",
    ".JuliaFormatter.toml",
    "Project.toml",
    "Manifest.toml",
    "docs/make.jl",
    "docs/Project.toml",
    "docs/Manifest.toml",
    "test/Project.toml",
    "test/Manifest.toml",
    "scripts/Project.toml",
    "scripts/Manifest.toml",
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert <gwr@bsl-support.de> and contributors"
SPDX-License-Identifier = "0BSD"
SPDX-FileComment = "This file is generated, project metadata, or other project infrastructure."

[[annotations]]
path = ["docs/src/assets/**"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert <gwr@bsl-support.de> and contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = "This file is content for the documentation."

[[annotations]]
path = ["README.md", "docs/*.md", "docs/src/**/*.md"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert <gwr@bsl-support.de> and contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = "This file is a documentation source file."

[[annotations]]
path = "data/spdx-license-list-data/**"
precedence = "closest"
SPDX-FileCopyrightText = "SPDX contributors to the SPDX License List"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "This file is part of a snapshot from https://github.com/spdx/license-list-data."

[[annotations]]
path = ["templates/*.mustache"]
precedence = "closest"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert <gwr@bsl-support.de> and contributors"
SPDX-License-Identifier = "0BSD"
SPDX-FileComment = "This file is a template file for package-level license declarations."

[[annotations]]
path = ["test/fixtures/packages/**"]
precedence = "override"
SPDX-FileCopyrightText = "2026 Guido Wolf Reichert <gwr@bsl-support.de> and contributors"
SPDX-License-Identifier = "0BSD"
SPDX-FileComment = "These files provide test packages with irrelevant local SPDX headers."
